version: "3.7"
services:
  app:
    build:
      context: ./docker/nim
      dockerfile: Dockerfile
    tty: true
    privileged: true
    volumes:
      - ./workspace:/opt/${PROJECT_NAME}
    working_dir: /opt/${PROJECT_NAME}